"""
core/tools/tavily_search.py
───────────────────────────
Web retrieval & auto-compilation pipeline.

Triggered when Nemotron identifies that external documentation,
recent GitHub issues, or live web context is needed.

Pipeline:
  1. Receive search query from Nano router
  2. Call Tavily Search API (async)
  3. Compile results into a Markdown document
  4. Save to ~/synapse_notes/<slug>.md (local filesystem)
  5. Return compiled text for injection into Ultra prompt

Qualifies for Tavily $3,000 Best Use side prize.
"""

import os
import re
import unicodedata
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

import httpx


TAVILY_API_URL = "https://api.tavily.com/search"
SYNAPSE_NOTES_DIR = Path.home() / "synapse_notes"


@dataclass
class TavilyResult:
    title: str
    url: str
    content: str
    score: float
    published_date: Optional[str] = None


@dataclass
class SearchOutput:
    query: str
    results: list[TavilyResult]
    compiled_markdown: str
    saved_path: Optional[str]
    search_ms: float
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def to_prompt_injection(self, max_chars: int = 1500) -> str:
        """Compact format for injecting into Ultra prompt."""
        lines = [f"[WEB RESEARCH — Tavily — {self.timestamp.strftime('%H:%M')}]",
                 f"Query: {self.query}", ""]
        for r in self.results[:3]:
            lines.append(f"Source: {r.url}")
            lines.append(r.content[:400])
            lines.append("")
        return "\n".join(lines)[:max_chars]


class TavilySearch:
    """
    Async Tavily Search API wrapper with auto-save to local Markdown.

    Usage:
        ts = TavilySearch()
        output = await ts.search("Python asyncio RuntimeError fix")
        # output.compiled_markdown — full compiled doc
        # output.saved_path       — where it was saved locally
        # output.to_prompt_injection() — for Ultra prompt
    """

    MAX_RESULTS = 5
    SEARCH_DEPTH = "advanced"  # "basic" | "advanced" — advanced costs 2 credits/call

    def __init__(self):
        self._api_key = self._load_api_key()
        SYNAPSE_NOTES_DIR.mkdir(parents=True, exist_ok=True)

    async def search(self, query: str, save: bool = True) -> SearchOutput:
        """
        Execute a Tavily search, compile results, and optionally save to disk.
        """
        import time
        t0 = time.perf_counter()

        payload = {
            "api_key": self._api_key,
            "query": query,
            "search_depth": self.SEARCH_DEPTH,
            "include_answer": True,
            "include_raw_content": False,
            "max_results": self.MAX_RESULTS,
        }

        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(TAVILY_API_URL, json=payload)
            resp.raise_for_status()
            data = resp.json()

        elapsed_ms = (time.perf_counter() - t0) * 1000

        results = [
            TavilyResult(
                title=r.get("title", ""),
                url=r.get("url", ""),
                content=r.get("content", ""),
                score=r.get("score", 0.0),
                published_date=r.get("published_date"),
            )
            for r in data.get("results", [])
        ]

        tavily_answer = data.get("answer", "")
        compiled = self._compile_markdown(query, results, tavily_answer)
        saved_path = None
        if save:
            saved_path = self._save_locally(query, compiled)

        return SearchOutput(
            query=query,
            results=results,
            compiled_markdown=compiled,
            saved_path=saved_path,
            search_ms=round(elapsed_ms, 1),
        )

    # ──────────────────────────────────────────────────────────────────
    # Internal
    # ──────────────────────────────────────────────────────────────────

    @staticmethod
    def _compile_markdown(query: str, results: list[TavilyResult], answer: str) -> str:
        ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            f"# Synapse Research: {query}",
            f"> Generated by Synapse via Tavily Search — {ts}",
            "",
        ]
        if answer:
            lines += ["## Summary", answer, ""]
        lines.append("## Sources")
        for i, r in enumerate(results, 1):
            lines += [
                f"### {i}. [{r.title}]({r.url})",
                f"*Score: {r.score:.2f}*",
                "",
                r.content,
                "",
            ]
        return "\n".join(lines)

    @staticmethod
    def _slugify(text: str) -> str:
        """Convert query to a safe filename slug."""
        text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
        text = re.sub(r"[^\w\s-]", "", text.lower())
        text = re.sub(r"[-\s]+", "-", text).strip("-")
        return text[:60]

    def _save_locally(self, query: str, content: str) -> str:
        slug = self._slugify(query)
        ts = datetime.utcnow().strftime("%Y%m%d_%H%M")
        filename = f"{ts}_{slug}.md"
        path = SYNAPSE_NOTES_DIR / filename
        path.write_text(content, encoding="utf-8")
        return str(path)

    @staticmethod
    def _load_api_key() -> str:
        key = os.environ.get("TAVILY_API_KEY")
        if key:
            return key
        try:
            import keyring
            key = keyring.get_password("synapse", "TAVILY_API_KEY")
            if key:
                return key
        except ImportError:
            pass
        raise ValueError("TAVILY_API_KEY not found in environment or Credential Manager")
